Extract API endpoint paths to api.properties file
CDCgov/trusted-intermediary pull request #400
Opened 2023-06-21 18:38 UTC by basiliskus

- Extracted API endpoint paths to `api.properties` file
- Considering moving the file to the root of the project so it's accessible by e2e tests

## Checklist

- [ ] I have added tests to cover my changes
- [ ] I have added logging where useful (with appropriate log level)
- [ ] I have added JavaDocs where required
- [ ] I have updated the documentation accordingly

2023-06-21 22:32 UTC, halprin requested changes
I like how you're thinking here, but we should keep our plugins separate from each other and separate from the main application.  By putting all the endpoints in a single properties file, we are violating that concept.

A couple of thoughts...

1. We could make multiple properties files, one for each plugin.  Does that still provide value as you see it?
2. We could change to a constant class.  I.e. a class that has nothing but `public static final String` fields.  We would still want to have one per plugin though.  E.g. `EtorEndpoints.DEMOGRAPHICS`.

What do you think about all this?

2023-06-26 14:25 UTC, halprin approved these changes
Sorry it took me this long to review your PR.  I have some feedback on the visibility of your constants, but it's not enough to not approve the PR.

2023-06-26 14:25 UTC, halprin commented on app/src/main/java/gov/hhs/cdc/trustedintermediary/auth/AuthDomainRegistration.java
> +    public static final String AUTH_API_ENDPOINT = "/v1/auth";
You can make these "package private" which will allow them to be used in tests but not outside the tests.

```suggestion
    static final String AUTH_API_ENDPOINT = "/v1/auth";
```

2023-06-26 14:25 UTC, halprin commented on app/src/main/java/gov/hhs/cdc/trustedintermediary/etor/EtorDomainRegistration.java
> +    public static final String ORDERS_API_ENDPOINT = "/v1/etor/orders";
You can make these "package private" which will allow them to be used in tests but not outside the tests.

```suggestion
    static final String DEMOGRAPHICS_API_ENDPOINT = "/v1/etor/demographics";
    static final String ORDERS_API_ENDPOINT = "/v1/etor/orders";
```

2023-06-26 15:41 UTC, jorg3lopez approved these changes
Looks good.

2023-06-26 15:43 UTC, merged