Refactor internal metadata step to use generics instead of empty interface
CDCgov/trusted-intermediary pull request #681
Opened 2023-11-23 19:45 UTC by basiliskus

# Refactor internal metadata step to use generics instead of empty interface

- Removed MetaDataStep interface
- Refactored to use generics instead of MetaDataStep interface:
  - `put` and `extractMetricsFromBundle` methods in `LoggingMetricMetaData` class, and `put` in `MetricMetaData` interface
  - `MetaDataEntry` record
  - Relevant test

## Issue

#680 

## Checklist

- [x] I have added tests to cover my changes
- [x] I have added logging where useful (with appropriate log level)
- [x] I have added JavaDocs where required
- [x] I have updated the documentation accordingly

2023-11-23 20:55 UTC, tjohnson7021 approved these changes

2023-11-27 15:31 UTC, jcrichlake approved these changes

2023-11-27 16:59 UTC, halprin requested changes
Nice!

2023-11-27 17:00 UTC, halprin approved these changes
lol, what did I click on?  GitHub is so hard to use.  🤦🏻‍♂️

2023-11-27 17:43 UTC, merged